const HP_PRODUCTS = [
  {
    "series": "鏄烞ook 14/15  AMD",
    "seriesKey": "starbook",
    "model": "HP 14-em0152AU",
    "pn": "7L4Y5PA",
    "cpu": "R5-7520U",
    "cpuBrand": "AMD",
    "ram": "16G",
    "storage": "512G SSD",
    "gpu": "UMA",
    "screen": "14.0",
    "resolution": "FHD",
    "color": "银色",
    "srp": 3599,
    "real": 2999,
    "cn2": "3356",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14/15  AMD",
    "seriesKey": "starbook",
    "model": "HP 14-em0352AU",
    "pn": "BG2W2PA",
    "cpu": "R5-7520U",
    "cpuBrand": "AMD",
    "ram": "16G",
    "storage": "512G SSD",
    "gpu": "UMA",
    "screen": "14.0",
    "resolution": "FHD",
    "color": "银色",
    "srp": 3599,
    "real": 3499,
    "cn2": "3356",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14/15  AMD",
    "seriesKey": "starbook",
    "model": "HP 14-em0157AU",
    "pn": "7Z1Q1PA",
    "cpu": "R5-7520U",
    "cpuBrand": "AMD",
    "ram": "16G",
    "storage": "1TB SSD",
    "gpu": "UMA",
    "screen": "14.0",
    "resolution": "FHD",
    "color": "银色",
    "srp": 3599,
    "real": 3299,
    "cn2": "3556",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14/15  AMD",
    "seriesKey": "starbook",
    "model": "HP 14-em0357AU",
    "pn": "BG2W3PA",
    "cpu": "R5-7520U",
    "cpuBrand": "AMD",
    "ram": "16G",
    "storage": "1TB SSD",
    "gpu": "UMA",
    "screen": "14.0",
    "resolution": "FHD",
    "color": "银色",
    "srp": 3599,
    "real": 3699,
    "cn2": "3556",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14/15  AMD",
    "seriesKey": "starbook",
    "model": "HP 14-em0170AU",
    "pn": "7L4Y6PA",
    "cpu": "R7-7730U",
    "cpuBrand": "AMD",
    "ram": "16G",
    "storage": "512G SSD",
    "gpu": "UMA",
    "screen": "14.0",
    "resolution": "FHD",
    "color": "银色",
    "srp": 4499,
    "real": 3899,
    "cn2": "4207",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14/15  AMD",
    "seriesKey": "starbook",
    "model": "HP 14-em0171AU",
    "pn": "7Z1Q2PA",
    "cpu": "R7-7730U",
    "cpuBrand": "AMD",
    "ram": "16G",
    "storage": "1TB SSD",
    "gpu": "UMA",
    "screen": "14.0",
    "resolution": "FHD",
    "color": "银色",
    "srp": 4299,
    "real": 3999,
    "cn2": "4408",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14/15  AMD",
    "seriesKey": "starbook",
    "model": "HP 14-em0172AU",
    "pn": "9H983PA",
    "cpu": "R7-7730U",
    "cpuBrand": "AMD",
    "ram": "16G",
    "storage": "1TB SSD",
    "gpu": "UMA",
    "screen": "14.0",
    "resolution": "FHD",
    "color": "银色",
    "srp": 3999,
    "real": 3599,
    "cn2": "3706",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14/15  AMD",
    "seriesKey": "starbook",
    "model": "HP 15-fc0259AU",
    "pn": "9P995PA",
    "cpu": "R5-7520U",
    "cpuBrand": "AMD",
    "ram": "8G",
    "storage": "512G SSD",
    "gpu": "UMA",
    "screen": "15.6",
    "resolution": "FHD",
    "color": "银色",
    "srp": 3099,
    "real": 2799,
    "cn2": "2905",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14/15  AMD",
    "seriesKey": "starbook",
    "model": "HP 15-fc0252AU",
    "pn": "7K3K4PA",
    "cpu": "R5-7520U",
    "cpuBrand": "AMD",
    "ram": "16G",
    "storage": "512G SSD",
    "gpu": "UMA",
    "screen": "15.6",
    "resolution": "FHD",
    "color": "银色",
    "srp": 3599,
    "real": 2999,
    "cn2": "3356",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14/15  AMD",
    "seriesKey": "starbook",
    "model": "HP 15-fc0258AU",
    "pn": "7Z1Q9PA",
    "cpu": "R5-7520U",
    "cpuBrand": "AMD",
    "ram": "16G",
    "storage": "1TB SSD",
    "gpu": "UMA",
    "screen": "15.6",
    "resolution": "FHD",
    "color": "银色",
    "srp": 3599,
    "real": 3199,
    "cn2": "3556",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14/15  AMD",
    "seriesKey": "starbook",
    "model": "HP 15-fc0459AU",
    "pn": "BL5P6PA",
    "cpu": "R5-7520U",
    "cpuBrand": "AMD",
    "ram": "8G",
    "storage": "512G SSD",
    "gpu": "UMA",
    "screen": "15.6",
    "resolution": "FHD",
    "color": "银色",
    "srp": 3099,
    "real": 3199,
    "cn2": "2905",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14/15  AMD",
    "seriesKey": "starbook",
    "model": "HP 15-fc0452AU",
    "pn": "BG2W8PA",
    "cpu": "R5-7520U",
    "cpuBrand": "AMD",
    "ram": "16G",
    "storage": "512G SSD",
    "gpu": "UMA",
    "screen": "15.6",
    "resolution": "FHD",
    "color": "银色",
    "srp": 3599,
    "real": 2999,
    "cn2": "3356",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14/15  AMD",
    "seriesKey": "starbook",
    "model": "HP 15-fc0458AU",
    "pn": "BG2W9PA",
    "cpu": "R5-7520U",
    "cpuBrand": "AMD",
    "ram": "16G",
    "storage": "1TB SSD",
    "gpu": "UMA",
    "screen": "15.6",
    "resolution": "FHD",
    "color": "银色",
    "srp": 3599,
    "real": 3699,
    "cn2": "3556",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14/15  AMD",
    "seriesKey": "starbook",
    "model": "HP 15-fc0271AU",
    "pn": "7K3K8PA",
    "cpu": "R7-7730U",
    "cpuBrand": "AMD",
    "ram": "16G",
    "storage": "512G SSD",
    "gpu": "UMA",
    "screen": "15.6",
    "resolution": "FHD",
    "color": "银色",
    "srp": 3699,
    "real": 3399,
    "cn2": "3807",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14/15  AMD",
    "seriesKey": "starbook",
    "model": "HP 15-fc0272AU",
    "pn": "7Z1R0PA",
    "cpu": "R7-7730U",
    "cpuBrand": "AMD",
    "ram": "16G",
    "storage": "1TB SSD",
    "gpu": "UMA",
    "screen": "15.6",
    "resolution": "FHD",
    "color": "银色",
    "srp": 3799,
    "real": 3599,
    "cn2": "4007",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14/15  AMD",
    "seriesKey": "starbook",
    "model": "HP 14-em0131AU",
    "pn": "7L4Y4PA",
    "cpu": "R3-7320U",
    "cpuBrand": "AMD",
    "ram": "8G",
    "storage": "512G SSD",
    "gpu": "UMA",
    "screen": "14.0",
    "resolution": "FHD",
    "color": "银色",
    "srp": 2699,
    "real": 2549,
    "cn2": "2504",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 16 2026",
    "seriesKey": "starbook",
    "model": "OmniBook 3 16-bu0152TU",
    "pn": "D41TZPA",
    "cpu": "Core 5-210H",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 5299,
    "real": 4499,
    "cn2": "4808",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 16 2026",
    "seriesKey": "starbook",
    "model": "OmniBook 3 16-bu0172TU",
    "pn": "D42C4PA",
    "cpu": "Core 7-240H",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 5699,
    "real": 4899,
    "cn2": "5209",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 16 2026",
    "seriesKey": "starbook",
    "model": "OmniBook 3 16-bu0173TU",
    "pn": "D42C5PA",
    "cpu": "Core 7-240H",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 6099,
    "real": 5299,
    "cn2": "5610",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 16 2026",
    "seriesKey": "starbook",
    "model": "OmniBook 3 16-bu0154TU",
    "pn": "D41U1PA",
    "cpu": "Core 5-210H",
    "cpuBrand": "Intel",
    "ram": "—",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 5699,
    "real": 4899,
    "cn2": "5209",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 16 2026",
    "seriesKey": "starbook",
    "model": "OmniBook 3 16-bu0155TU",
    "pn": "D41U2PA",
    "cpu": "Core 5-210H",
    "cpuBrand": "Intel",
    "ram": "—",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 6099,
    "real": 5299,
    "cn2": "5610",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 16 2026",
    "seriesKey": "starbook",
    "model": "OmniBook 3 16-bu0553TU",
    "pn": "D6BN6PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 5699,
    "real": 4899,
    "cn2": "5209",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14 2026",
    "seriesKey": "starbookultra",
    "model": "OmniBook 3 14-hu0052TU",
    "pn": "D61D1PA",
    "cpu": "Core 5-210H",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 5299,
    "real": 4499,
    "cn2": "4808",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14 2026",
    "seriesKey": "starbookultra",
    "model": "OmniBook 3 14-hu0053TU",
    "pn": "D61D2PA",
    "cpu": "Core 5-210H",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 5699,
    "real": 4899,
    "cn2": "5209",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14 2026",
    "seriesKey": "starbookultra",
    "model": "OmniBook 3 14-hu0072TU",
    "pn": "D61D4PA",
    "cpu": "Core 7-240H",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 5699,
    "real": 4899,
    "cn2": "5209",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14 2026",
    "seriesKey": "starbookultra",
    "model": "OmniBook 3 14-hu0073TU",
    "pn": "D61D5PA",
    "cpu": "Core 7-240H",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 6099,
    "real": 5299,
    "cn2": "5610",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14 2026",
    "seriesKey": "starbookultra",
    "model": "OmniBook 3 14-hu0063TU",
    "pn": "D61D3PA",
    "cpu": "Core 5-210H",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 6099,
    "real": 5399,
    "cn2": "5610",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14 INTEL 2024",
    "seriesKey": "starbook",
    "model": "HP 14-ep0336TU",
    "pn": "A9HZ2PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "8G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0",
    "resolution": "FHD",
    "color": "银色",
    "srp": 2699,
    "real": 2699,
    "cn2": "2504",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14 INTEL 2024",
    "seriesKey": "starbook",
    "model": "HP 14-ep0337TU",
    "pn": "A9HZ3PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "8G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0",
    "resolution": "FHD",
    "color": "银色",
    "srp": 2899,
    "real": 2899,
    "cn2": "2705",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14 INTEL 2024",
    "seriesKey": "starbook",
    "model": "HP 14-ep0537TU",
    "pn": "BG2W4PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "8G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0",
    "resolution": "FHD",
    "color": "银色",
    "srp": 2899,
    "real": 2899,
    "cn2": "2705",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14 INTEL 2024",
    "seriesKey": "starbook",
    "model": "HP 14-ep0777TU",
    "pn": "A85N9PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0",
    "resolution": "FHD",
    "color": "银色",
    "srp": 3699,
    "real": 3199,
    "cn2": "3506",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 15 INTEL 2024",
    "seriesKey": "starbook",
    "model": "HP 15-fd0889TU",
    "pn": "AQ3K3PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "15.6",
    "resolution": "FHD",
    "color": "银色",
    "srp": 3999,
    "real": 3399,
    "cn2": "3807",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 15 INTEL 2024",
    "seriesKey": "starbook",
    "model": "HP 15-fd0888TU",
    "pn": "A5LL0PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "15.6",
    "resolution": "FHD",
    "color": "银色",
    "srp": 3699,
    "real": 3199,
    "cn2": "3506",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 15 2025",
    "seriesKey": "starbook",
    "model": "HP 15-fr0660TU",
    "pn": "BR2N6PA",
    "cpu": "i5-13500H",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "512G SSD",
    "gpu": "UMA",
    "screen": "15.6",
    "resolution": "FHD",
    "color": "银色",
    "srp": 3999,
    "real": 3999,
    "cn2": "3707",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 15 2025",
    "seriesKey": "starbook",
    "model": "HP 15-fr0661TU",
    "pn": "D2JD7PA",
    "cpu": "i5-13500H",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "15.6",
    "resolution": "FHD",
    "color": "银色",
    "srp": 3999,
    "real": 3599,
    "cn2": "3707",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 15 2025",
    "seriesKey": "starbook",
    "model": "HP 15-fr0662TU",
    "pn": "BR2N7PA",
    "cpu": "i5-13500H",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "1TB SSD",
    "gpu": "UMA",
    "screen": "15.6",
    "resolution": "FHD",
    "color": "银色",
    "srp": 4299,
    "real": 4199,
    "cn2": "4007",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 15 2025",
    "seriesKey": "starbook",
    "model": "HP 15-fr0664TU",
    "pn": "D2JD8PA",
    "cpu": "i5-13500H",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "15.6",
    "resolution": "FHD",
    "color": "银色",
    "srp": 4299,
    "real": 3799,
    "cn2": "4007",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 15 2025",
    "seriesKey": "starbook",
    "model": "HP 15-fr0680TU",
    "pn": "BR2N8PA",
    "cpu": "i7-13620H",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "512G SSD",
    "gpu": "UMA",
    "screen": "15.6",
    "resolution": "FHD",
    "color": "银色",
    "srp": 4499,
    "real": 3899,
    "cn2": "4107",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 15 2025",
    "seriesKey": "starbook",
    "model": "HP 15-fr0682TU",
    "pn": "BR2N9PA",
    "cpu": "i7-13620H",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "1TB SSD",
    "gpu": "UMA",
    "screen": "15.6",
    "resolution": "FHD",
    "color": "银色",
    "srp": 4799,
    "real": 4599,
    "cn2": "4408",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 15 2025",
    "seriesKey": "starbook",
    "model": "HP 15-fr0782TU",
    "pn": "D2HZ4PA",
    "cpu": "i7-13620H",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "15.6",
    "resolution": "FHD",
    "color": "银色",
    "srp": 4799,
    "real": 4599,
    "cn2": "4408",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 15 Ultra 2024",
    "seriesKey": "starbook",
    "model": "聽HP 15-fd1850TU",
    "pn": "A19U4PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "15.6",
    "resolution": "FHD",
    "color": "银色",
    "srp": 4599,
    "real": 3599,
    "cn2": "4207",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 15 Ultra 2024",
    "seriesKey": "starbook",
    "model": "HP 15-fd1250TU",
    "pn": "BG2X0PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "15.6",
    "resolution": "FHD",
    "color": "银色",
    "srp": 4599,
    "real": 4099,
    "cn2": "4207",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 15 Ultra 2024",
    "seriesKey": "starbook",
    "model": "HP 15-fd1550TU",
    "pn": "D14WSPA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "15.6",
    "resolution": "FHD",
    "color": "银色",
    "srp": 4099,
    "real": 4399,
    "cn2": "3906.8",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 15 Ultra 2024",
    "seriesKey": "starbook",
    "model": "聽HP 15-fd1852TU",
    "pn": "A19U5PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "15.6",
    "resolution": "FHD",
    "color": "银色",
    "srp": 5099,
    "real": 4099,
    "cn2": "4708",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 15 Ultra 2024",
    "seriesKey": "starbook",
    "model": "聽HP 15-fd1870TU",
    "pn": "A19U6PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "15.6",
    "resolution": "FHD",
    "color": "银色",
    "srp": 5199,
    "real": 4299,
    "cn2": "4808",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 15 Ultra 2024",
    "seriesKey": "starbook",
    "model": "HP 15-fd1252TU",
    "pn": "BG2X1PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "15.6",
    "resolution": "FHD",
    "color": "银色",
    "srp": 5099,
    "real": 4199,
    "cn2": "4708",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 15 Ultra 2024",
    "seriesKey": "starbook",
    "model": "HP 15-fd1270TU",
    "pn": "BG2X2PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "15.6",
    "resolution": "FHD",
    "color": "银色",
    "srp": 5199,
    "real": 4399,
    "cn2": "4808",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14 Ultr a2024",
    "seriesKey": "starbookultra",
    "model": "HP 14-ep1754TU",
    "pn": "A51TGPA",
    "cpu": "4199",
    "cpuBrand": "Intel",
    "ram": "—",
    "storage": "16G",
    "gpu": "UMA",
    "screen": "UMA",
    "resolution": "FHD",
    "color": "银色",
    "srp": 5,
    "real": 99,
    "cn2": "4708",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14 Ultr a2024",
    "seriesKey": "starbookultra",
    "model": "HP 14-ep1954TU",
    "pn": "BG2Y9PA",
    "cpu": "4199",
    "cpuBrand": "Intel",
    "ram": "—",
    "storage": "16G",
    "gpu": "UMA",
    "screen": "UMA",
    "resolution": "FHD",
    "color": "银色",
    "srp": 5,
    "real": 99,
    "cn2": "4708",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14 Ultr a2024",
    "seriesKey": "starbookultra",
    "model": "HP 14-ep1759TU",
    "pn": "A51THPA",
    "cpu": "4399",
    "cpuBrand": "Intel",
    "ram": "—",
    "storage": "32G",
    "gpu": "UMA",
    "screen": "UMA",
    "resolution": "FHD",
    "color": "银色",
    "srp": 5,
    "real": 599,
    "cn2": "5209",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14 Ultr a2024",
    "seriesKey": "starbookultra",
    "model": "HP 14-ep1959TU",
    "pn": "BG2Z0PA",
    "cpu": "4699",
    "cpuBrand": "Intel",
    "ram": "—",
    "storage": "32G",
    "gpu": "UMA",
    "screen": "UMA",
    "resolution": "FHD",
    "color": "银色",
    "srp": 5,
    "real": 599,
    "cn2": "5209",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14 Ultr a2024",
    "seriesKey": "starbookultra",
    "model": "HP 14-ep1774TU",
    "pn": "A51TJPA",
    "cpu": "4599",
    "cpuBrand": "Intel",
    "ram": "—",
    "storage": "16G",
    "gpu": "UMA",
    "screen": "UMA",
    "resolution": "FHD",
    "color": "银色",
    "srp": 5,
    "real": 699,
    "cn2": "5309",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14 Ultr a2024",
    "seriesKey": "starbookultra",
    "model": "HP 14-ep1750TU",
    "pn": "A19U0PA",
    "cpu": "3499",
    "cpuBrand": "Intel",
    "ram": "—",
    "storage": "16G",
    "gpu": "UMA",
    "screen": "UMA",
    "resolution": "FHD",
    "color": "银色",
    "srp": 4,
    "real": 499,
    "cn2": "4107",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14 Ultr a2024",
    "seriesKey": "starbookultra",
    "model": "HP 14-ep1950TU",
    "pn": "BG2W5PA",
    "cpu": "4099",
    "cpuBrand": "Intel",
    "ram": "—",
    "storage": "16G",
    "gpu": "UMA",
    "screen": "UMA",
    "resolution": "FHD",
    "color": "银色",
    "srp": 4,
    "real": 499,
    "cn2": "4107",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14 Ultr a2024",
    "seriesKey": "starbookultra",
    "model": "HP 14-ep1440TU",
    "pn": "CU6V8PA",
    "cpu": "4399",
    "cpuBrand": "Intel",
    "ram": "—",
    "storage": "16G",
    "gpu": "UMA",
    "screen": "UMA",
    "resolution": "FHD",
    "color": "银色",
    "srp": 907,
    "real": 4099,
    "cn2": "3",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14 Ultr a2024",
    "seriesKey": "starbookultra",
    "model": "HP 14-ep1752TU",
    "pn": "A19U1PA",
    "cpu": "4099",
    "cpuBrand": "Intel",
    "ram": "—",
    "storage": "32G",
    "gpu": "UMA",
    "screen": "UMA",
    "resolution": "FHD",
    "color": "银色",
    "srp": 4,
    "real": 999,
    "cn2": "4608",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14 Ultr a2024",
    "seriesKey": "starbookultra",
    "model": "HP 14-ep1952TU",
    "pn": "BG2W6PA",
    "cpu": "4199",
    "cpuBrand": "Intel",
    "ram": "—",
    "storage": "32G",
    "gpu": "UMA",
    "screen": "UMA",
    "resolution": "FHD",
    "color": "银色",
    "srp": 4,
    "real": 999,
    "cn2": "4608",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14 Ultr a2024",
    "seriesKey": "starbookultra",
    "model": "HP 14-ep1770TU",
    "pn": "A19U2PA",
    "cpu": "4299",
    "cpuBrand": "Intel",
    "ram": "—",
    "storage": "16G",
    "gpu": "UMA",
    "screen": "UMA",
    "resolution": "FHD",
    "color": "银色",
    "srp": 5,
    "real": 99,
    "cn2": "4708",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄烞ook 14 Ultr a2024",
    "seriesKey": "starbookultra",
    "model": "HP 14-ep1970TU",
    "pn": "BG2W7PA",
    "cpu": "4399",
    "cpuBrand": "Intel",
    "ram": "—",
    "storage": "16G",
    "gpu": "UMA",
    "screen": "UMA",
    "resolution": "FHD",
    "color": "银色",
    "srp": 5,
    "real": 99,
    "cn2": "4708",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄 Book Pro 14  2024",
    "seriesKey": "pavilionplus",
    "model": "Pavilion Plus 14-ew1050TU",
    "pn": "9R272PA",
    "cpu": "—",
    "cpuBrand": "AMD",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0",
    "resolution": "FHD",
    "color": "银色",
    "srp": 5999,
    "real": 4899,
    "cn2": "5610",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄 Book Pro 14  2024",
    "seriesKey": "pavilionplus",
    "model": "Pavilion Plus 14-ew1051TU",
    "pn": "9R271PA",
    "cpu": "—",
    "cpuBrand": "AMD",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0",
    "resolution": "FHD",
    "color": "银色",
    "srp": 6499,
    "real": 5299,
    "cn2": "6111",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄 Book Pro 14  2024",
    "seriesKey": "pavilionplus",
    "model": "Pavilion Plus 14-ew1151TU",
    "pn": "BF5P4PA",
    "cpu": "—",
    "cpuBrand": "AMD",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0",
    "resolution": "FHD",
    "color": "银色",
    "srp": 6499,
    "real": 5299,
    "cn2": "6111",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄 Book Pro 14  2024",
    "seriesKey": "pavilionplus",
    "model": "Pavilion Plus 14-ew1054TU",
    "pn": "9R276PA",
    "cpu": "—",
    "cpuBrand": "AMD",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 7399,
    "real": 5799,
    "cn2": "6912",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄 Book Pro 14  2024",
    "seriesKey": "pavilionplus",
    "model": "Pavilion Plus 14-ew1055TU",
    "pn": "9R277PA",
    "cpu": "—",
    "cpuBrand": "AMD",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0",
    "resolution": "FHD",
    "color": "蓝色",
    "srp": 5999,
    "real": 5099,
    "cn2": "5610",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄 Book Pro 14  2024",
    "seriesKey": "pavilionplus",
    "model": "Pavilion Plus 14-ew1059TU",
    "pn": "9R281PA",
    "cpu": "—",
    "cpuBrand": "AMD",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "蓝色",
    "srp": 7399,
    "real": 5799,
    "cn2": "6912",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄 Book Pro 14  2024",
    "seriesKey": "pavilionplus",
    "model": "Pavilion Plus 14-ew1060TU",
    "pn": "9R282PA",
    "cpu": "—",
    "cpuBrand": "AMD",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0",
    "resolution": "FHD",
    "color": "银色",
    "srp": 5999,
    "real": 4999,
    "cn2": "5610",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄 Book Pro 14  2024",
    "seriesKey": "pavilionplus",
    "model": "Pavilion Plus 14-ew1064TU",
    "pn": "9R286PA",
    "cpu": "—",
    "cpuBrand": "AMD",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 7399,
    "real": 5899,
    "cn2": "6912",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄烞ook Pro 14 2025",
    "seriesKey": "starbookpro",
    "model": "OmniBook 7 14-fs0013TU",
    "pn": "BK6F0PA",
    "cpu": "Core 5-210H",
    "cpuBrand": "AMD",
    "ram": "—",
    "storage": "—",
    "gpu": "UMA",
    "screen": "",
    "resolution": "FHD",
    "color": "银色",
    "srp": 5699,
    "real": 4999,
    "cn2": "5109",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄烞ook Pro 14 2025",
    "seriesKey": "starbookpro",
    "model": "OmniBook 7 14-fs0021TU",
    "pn": "BK6H9PA",
    "cpu": "Core5-220H",
    "cpuBrand": "AMD",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 5599,
    "real": 4799,
    "cn2": "5009",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄烞ook Pro 14 2025",
    "seriesKey": "starbookpro",
    "model": "OmniBook 7 14-fs0023TU",
    "pn": "BK6D8PA",
    "cpu": "Core5-220H",
    "cpuBrand": "AMD",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "",
    "resolution": "FHD",
    "color": "银色",
    "srp": 6199,
    "real": 5599,
    "cn2": "5610",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄烞ook Pro 14 2025",
    "seriesKey": "starbookpro",
    "model": "OmniBook 7 14-fs0024TU",
    "pn": "BK7F8PA",
    "cpu": "Core5-220H",
    "cpuBrand": "AMD",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 5899,
    "real": 5399,
    "cn2": "5309",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄烞ook Pro 14 2025",
    "seriesKey": "starbookpro",
    "model": "OmniBook 7 14-fs0026TU",
    "pn": "BK7F9PA",
    "cpu": "Core5-220H",
    "cpuBrand": "AMD",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 6499,
    "real": 5899,
    "cn2": "5910",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄烞ook Pro 14 2025",
    "seriesKey": "starbookpro",
    "model": "OmniBook 7 14-fs0027TU",
    "pn": "BK7H6PA",
    "cpu": "Core9-270H",
    "cpuBrand": "AMD",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 7299,
    "real": 6999,
    "cn2": "6612",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄烞ook Pro 14 2025",
    "seriesKey": "starbookpro",
    "model": "OmniBook 7 14-fs0028TU",
    "pn": "BK7G0PA",
    "cpu": "Core9-270H",
    "cpuBrand": "AMD",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 7299,
    "real": 6999,
    "cn2": "6612",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄烞ook Pro 14 2025",
    "seriesKey": "starbookpro",
    "model": "OmniBook 7 14-fr0040TU",
    "pn": "BK7G6PA",
    "cpu": "R57467",
    "cpuBrand": "AMD",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 6399,
    "real": 5599,
    "cn2": "5810",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄烞ook Pro 14 2025",
    "seriesKey": "starbookpro",
    "model": "OmniBook 7 14-fr0041TU",
    "pn": "BK7F1PA",
    "cpu": "R57467",
    "cpuBrand": "AMD",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 7499,
    "real": 6899,
    "cn2": "6812",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄烞ook Pro 14 2025",
    "seriesKey": "starbookpro",
    "model": "OmniBook 7 14-fr0042TU",
    "pn": "BR4H9PA",
    "cpu": "R57467",
    "cpuBrand": "AMD",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 6399,
    "real": 5699,
    "cn2": "5810",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄烞ook Pro 14 2025",
    "seriesKey": "starbookpro",
    "model": "OmniBook 7 14-fr0043TU",
    "pn": "BR4P8PA",
    "cpu": "R57467",
    "cpuBrand": "AMD",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 7499,
    "real": 6999,
    "cn2": "6812",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄烞ook Pro 14 2025",
    "seriesKey": "starbookpro",
    "model": "OmniBook 7 14-fs0044TU",
    "pn": "BR4J0PA",
    "cpu": "Core5-220H",
    "cpuBrand": "AMD",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 5899,
    "real": 5399,
    "cn2": "5309",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄烞ook Pro 14 2025",
    "seriesKey": "starbookpro",
    "model": "OmniBook 7 14-fs0046TU",
    "pn": "BR4J2PA",
    "cpu": "Core5-220H",
    "cpuBrand": "AMD",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 6499,
    "real": 5899,
    "cn2": "5910",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄烞ook Pro 14 2025",
    "seriesKey": "starbookpro",
    "model": "OmniBook 7 14-fs0047TU",
    "pn": "BR4J3PA",
    "cpu": "Core5-220H",
    "cpuBrand": "AMD",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 5899,
    "real": 5499,
    "cn2": "5309",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄烞ook Pro 14 2025",
    "seriesKey": "starbookpro",
    "model": "OmniBook 7 14-fs0049TU",
    "pn": "BR4J5PA",
    "cpu": "Core5-220H",
    "cpuBrand": "AMD",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 6499,
    "real": 5999,
    "cn2": "5910",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄烞ook Pro 14 2025",
    "seriesKey": "starbookpro",
    "model": "OmniBook 7 14-fr0051TU",
    "pn": "C52G4PA",
    "cpu": "6299",
    "cpuBrand": "Intel",
    "ram": "—",
    "storage": "32G",
    "gpu": "UMA",
    "screen": "UMA",
    "resolution": "FHD",
    "color": "银色",
    "srp": 416,
    "real": 6999,
    "cn2": "6",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄烞ook Pro 14 2025",
    "seriesKey": "starbookpro",
    "model": "OmniBook 7 14-fr0052TU",
    "pn": "C52G5PA",
    "cpu": "6399",
    "cpuBrand": "Intel",
    "ram": "—",
    "storage": "32G",
    "gpu": "UMA",
    "screen": "UMA",
    "resolution": "FHD",
    "color": "银色",
    "srp": 416,
    "real": 6999,
    "cn2": "6",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "鏄焍ook pro 13 2025",
    "seriesKey": "starbook",
    "model": "Omni Book 7 13-bg1077AU",
    "pn": "B91C9PA",
    "cpu": "—",
    "cpuBrand": "AMD",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "",
    "resolution": "FHD",
    "color": "银色",
    "srp": 7299,
    "real": 6999,
    "cn2": "6812",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄焍ook pro 13 2025",
    "seriesKey": "starbook",
    "model": "Omni Book 7 13-bg1078AU",
    "pn": "B91CBPA",
    "cpu": "—",
    "cpuBrand": "AMD",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "",
    "resolution": "FHD",
    "color": "银色",
    "srp": 7299,
    "real": 7099,
    "cn2": "6812",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook Pro 16 2025",
    "seriesKey": "starbook",
    "model": "Omni Book 7 16-az0052TU",
    "pn": "BE7K5PA",
    "cpu": "Core 5-210H",
    "cpuBrand": "AMD",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 5699,
    "real": 5299,
    "cn2": "5109",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook Pro 16 2025",
    "seriesKey": "starbook",
    "model": "Omni Book 7 16-az0062TU",
    "pn": "BE7K7PA",
    "cpu": "Core5-220H",
    "cpuBrand": "AMD",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 5899,
    "real": 5499,
    "cn2": "5309",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook Pro 16 2025",
    "seriesKey": "starbook",
    "model": "Omni Book 7 16-az0064TU",
    "pn": "BE7K9PA",
    "cpu": "Core5-220H",
    "cpuBrand": "AMD",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 6499,
    "real": 5999,
    "cn2": "5910",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook Pro 16 2025",
    "seriesKey": "starbook",
    "model": "Omni Book 7 16-az0065TU",
    "pn": "BE7L0PA",
    "cpu": "Core9-270H",
    "cpuBrand": "AMD",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 7299,
    "real": 6999,
    "cn2": "6612",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook Pro 16 2025",
    "seriesKey": "starbook",
    "model": "Omni Book 7 16-az0066TU",
    "pn": "BK0C1PA",
    "cpu": "Core 7-240H",
    "cpuBrand": "AMD",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 6099,
    "real": 5699,
    "cn2": "5510",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook Pro 16 2025",
    "seriesKey": "starbook",
    "model": "Omni Book 7 16-az0068TU",
    "pn": "BK0C3PA",
    "cpu": "Core 7-240H",
    "cpuBrand": "AMD",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 6699,
    "real": 6199,
    "cn2": "6111",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook Pro 16 2025",
    "seriesKey": "starbook",
    "model": "Omni Book 7 16-ay0070TU",
    "pn": "BF2A6PA",
    "cpu": "R57467",
    "cpuBrand": "AMD",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 6399,
    "real": 5599,
    "cn2": "5810",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook Pro 16 2025",
    "seriesKey": "starbook",
    "model": "OmniBook 7 16-ay0073TU",
    "pn": "C74VQPA",
    "cpu": "R57467",
    "cpuBrand": "AMD",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 6999,
    "real": 6299,
    "cn2": "6411",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook Pro 16 2025",
    "seriesKey": "starbook",
    "model": "Omni Book 7 16-az0080TU",
    "pn": "BR4M8PA",
    "cpu": "Core5-220H",
    "cpuBrand": "AMD",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 5899,
    "real": 5499,
    "cn2": "5309",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook Pro 16 2025",
    "seriesKey": "starbook",
    "model": "Omni Book 7 16-az0082TU",
    "pn": "BR4J7PA",
    "cpu": "Core5-220H",
    "cpuBrand": "AMD",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 6499,
    "real": 5999,
    "cn2": "5910",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook Pro 16 2025",
    "seriesKey": "starbook",
    "model": "Omni Book 7 16-az0085TU",
    "pn": "BR4J8PA",
    "cpu": "Core9-270H",
    "cpuBrand": "AMD",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 7299,
    "real": 6999,
    "cn2": "6612",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook Pro 16 2025",
    "seriesKey": "starbook",
    "model": "Omni Book 7 16-az0086TU",
    "pn": "BR4J9PA",
    "cpu": "Core 7-240H",
    "cpuBrand": "AMD",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 6099,
    "real": 5699,
    "cn2": "5510",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook Pro 16 2025",
    "seriesKey": "starbook",
    "model": "Omni Book 7 16-az0088TU",
    "pn": "BR4K1PA",
    "cpu": "Core 7-240H",
    "cpuBrand": "AMD",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 6699,
    "real": 6199,
    "cn2": "6111",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook Pro 16 2026",
    "seriesKey": "starbook",
    "model": "OmniBook 7 16-bh0093TU",
    "pn": "D44P6PA",
    "cpu": "—",
    "cpuBrand": "AMD",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 8099,
    "real": 7999,
    "cn2": "8114",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "P14 X360 2024",
    "seriesKey": "pavilionx360",
    "model": "Pavlion x360 14-ek2080TU",
    "pn": "A20A5PA",
    "cpu": "3899",
    "cpuBrand": "Intel",
    "ram": "—",
    "storage": "8G",
    "gpu": "UMA",
    "screen": "UMA",
    "resolution": "FHD",
    "color": "银色",
    "srp": 807,
    "real": 3899,
    "cn2": "3",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "P14 X360 2024",
    "seriesKey": "pavilionx360",
    "model": "Pavlion x360 14-ek2081TU",
    "pn": "A20A6PA",
    "cpu": "4999",
    "cpuBrand": "Intel",
    "ram": "—",
    "storage": "16G",
    "gpu": "UMA",
    "screen": "UMA",
    "resolution": "FHD",
    "color": "银色",
    "srp": 9,
    "real": 5399,
    "cn2": "5",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "P14 X360 2024",
    "seriesKey": "pavilionx360",
    "model": "Pavlion x360 14-ek2082TU",
    "pn": "A20A7PA",
    "cpu": "5799",
    "cpuBrand": "Intel",
    "ram": "—",
    "storage": "16G",
    "gpu": "UMA",
    "screen": "UMA",
    "resolution": "FHD",
    "color": "银色",
    "srp": 810,
    "real": 6199,
    "cn2": "5",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "ENVY 绯诲垪(2024锛",
    "seriesKey": "envy",
    "model": "聽ENVY x360 14-fc0110TU",
    "pn": "9X7H4PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 7499,
    "real": 7499,
    "cn2": "6812",
    "segment": "premium",
    "highlight": true
  },
  {
    "series": "ENVY 绯诲垪(2024锛",
    "seriesKey": "envy",
    "model": "聽ENVY x360 14-fc0111TU",
    "pn": "9X7H5PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 7599,
    "real": 7499,
    "cn2": "6812",
    "segment": "premium",
    "highlight": true
  },
  {
    "series": "ENVY 绯诲垪(2024锛",
    "seriesKey": "envy",
    "model": "聽ENVY x360 14-fc0112TU",
    "pn": "9X7H6PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 8299,
    "real": 8299,
    "cn2": "7613",
    "segment": "premium",
    "highlight": true
  },
  {
    "series": "ENVY 绯诲垪(2024锛",
    "seriesKey": "envy",
    "model": "聽ENVY x360 14-fc0113TU",
    "pn": "9X7H7PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 8399,
    "real": 8299,
    "cn2": "7613",
    "segment": "premium",
    "highlight": true
  },
  {
    "series": "ENVY 绯诲垪(2024锛",
    "seriesKey": "envy",
    "model": "聽ENVY x360 14-fc0115TU",
    "pn": "9X7H8PA",
    "cpu": "—",
    "cpuBrand": "AMD",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 8999,
    "real": 8999,
    "cn2": "8214",
    "segment": "premium",
    "highlight": true
  },
  {
    "series": "ENVY 绯诲垪(2024锛",
    "seriesKey": "envy",
    "model": "聽ENVY x360 14-fc0116TU",
    "pn": "9X7H9PA",
    "cpu": "—",
    "cpuBrand": "AMD",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 8999,
    "real": 8999,
    "cn2": "8214",
    "segment": "premium",
    "highlight": true
  },
  {
    "series": "ENVY 绯诲垪(2024锛",
    "seriesKey": "envy",
    "model": "聽ENVY x360 14-fa0110AU",
    "pn": "9X7P4PA",
    "cpu": "R5-8640H",
    "cpuBrand": "AMD",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 6499,
    "real": 6199,
    "cn2": "6010",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "ENVY 绯诲垪(2024锛",
    "seriesKey": "envy",
    "model": "聽ENVY x360 14-fa0111AU",
    "pn": "9X7H2PA",
    "cpu": "R7-8840H",
    "cpuBrand": "AMD",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 6999,
    "real": 6699,
    "cn2": "6411",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "ENVY 绯诲垪(2024锛",
    "seriesKey": "envy",
    "model": "聽ENVY x360 14-fa0112AU",
    "pn": "9X7H3PA",
    "cpu": "R7-8840H",
    "cpuBrand": "AMD",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 6999,
    "real": 6699,
    "cn2": "6411",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "ENVY 绯诲垪(2024锛",
    "seriesKey": "envy",
    "model": "聽ENVY x360 14-fa0113AU",
    "pn": "9Z196PA",
    "cpu": "R7-8840H",
    "cpuBrand": "AMD",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 7499,
    "real": 6999,
    "cn2": "6912",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "ENVY 绯诲垪(2024锛",
    "seriesKey": "envy",
    "model": "聽ENVY x360 16-ad0007AU",
    "pn": "9X2S6PA",
    "cpu": "R7-8840H",
    "cpuBrand": "AMD",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 7999,
    "real": 7499,
    "cn2": "7213",
    "segment": "premium",
    "highlight": true
  },
  {
    "series": "聽ENVY x360 14 2024",
    "seriesKey": "envy",
    "model": "聽ENVY x360 14-fa0131AU",
    "pn": "BF0Z7PA",
    "cpu": "R5-8640H",
    "cpuBrand": "AMD",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 6199,
    "real": 5999,
    "cn2": "5840",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "聽ENVY x360 14 2024",
    "seriesKey": "envy",
    "model": "聽ENVY x360 14-fa0130AU",
    "pn": "BF0Z6PA",
    "cpu": "R7-8840H",
    "cpuBrand": "AMD",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 6999,
    "real": 6799,
    "cn2": "6591",
    "segment": "premium",
    "highlight": false
  },
  {
    "series": "聽鏄烞ook X 14 2025",
    "seriesKey": "starbook",
    "model": "聽HP OmniBook X Flip 14-fm0000TU",
    "pn": "B91CDPA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "1TB SSD",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 8999,
    "real": 8499,
    "cn2": "8294",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "聽鏄烞ook X 14 2025",
    "seriesKey": "starbook",
    "model": "聽HP OmniBook X Flip 14-fm0001TU",
    "pn": "B91CFPA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "1TB SSD",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 8899,
    "real": 8399,
    "cn2": "8204",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "聽鏄烞ook X 14 2025",
    "seriesKey": "starbook",
    "model": "HP OmniBook X Flip 14-fm0002TU",
    "pn": "C44ZTPA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "1TB SSD",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 7399,
    "real": 7099,
    "cn2": "6822",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "聽鏄烞ook X 14 2025",
    "seriesKey": "starbook",
    "model": "聽HP OmniBook X Flip 14-fm0003TU",
    "pn": "B91BNPA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "1TB SSD",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 7299,
    "real": 6999,
    "cn2": "6727",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "聽鏄烞ook X 14 AMD 2025",
    "seriesKey": "starbook",
    "model": "聽HP OmniBook X Flip 14-fk0001AU",
    "pn": "B9NV6PA",
    "cpu": "—",
    "cpuBrand": "AMD",
    "ram": "32G",
    "storage": "1TB SSD",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 7799,
    "real": 7799,
    "cn2": "7188",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "聽鏄烞ook X 14 AMD 2025",
    "seriesKey": "starbook",
    "model": "聽HP OmniBook X Flip 14-fk0015AU",
    "pn": "B9NV8PA",
    "cpu": "—",
    "cpuBrand": "AMD",
    "ram": "—",
    "storage": "1TB SSD",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 7399,
    "real": 7399,
    "cn2": "6822",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "聽鏄烞ook X 14 AMD 2025",
    "seriesKey": "starbook",
    "model": "聽HP OmniBook X Flip 14-fk0000AU",
    "pn": "B9LS9PA",
    "cpu": "—",
    "cpuBrand": "AMD",
    "ram": "16G",
    "storage": "1TB SSD",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 6499,
    "real": 6499,
    "cn2": "5990",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook X 14 2026",
    "seriesKey": "starbook",
    "model": "HP OmniBook X 14-ka0005TU",
    "pn": "D44QGPA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 14999,
    "real": 8699,
    "cn2": "13273",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook X 14 2026",
    "seriesKey": "starbook",
    "model": "HP OmniBook X 14-ka0025TU",
    "pn": "D44QTPA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 11999,
    "real": 7899,
    "cn2": "10438",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook X 360 14 2026",
    "seriesKey": "starbook",
    "model": "HP OmniBook X 14-kb0004TU",
    "pn": "D44QQPA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 14999,
    "real": 8999,
    "cn2": "13614",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook X 360 14 2026",
    "seriesKey": "starbook",
    "model": "HP OmniBook X 14-kb0006TU",
    "pn": "D44PGPA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 18499,
    "real": 10699,
    "cn2": "16419",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook X 360 14 2026",
    "seriesKey": "starbook",
    "model": "HP OmniBook X 14-kb0008TU",
    "pn": "D44PHPA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 15999,
    "real": 9999,
    "cn2": "14435",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook X 360 16 2026",
    "seriesKey": "starbook",
    "model": "HP OmniBook X 16-cb0006TU",
    "pn": "D43MRPA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 15999,
    "real": 9499,
    "cn2": "14024",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook X 360 16 2026",
    "seriesKey": "starbook",
    "model": "HP OmniBook X 16-cb0005TU",
    "pn": "D43MQPA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 16999,
    "real": 10499,
    "cn2": "14856",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook X 360 16 2026",
    "seriesKey": "starbook",
    "model": "HP OmniBook X 16-cb0004TU",
    "pn": "D43MPPA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 18999,
    "real": 11499,
    "cn2": "16849",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook X 360 14 AMD 2026",
    "seriesKey": "starbook",
    "model": "HP OmniBook X 14-kc0001AU",
    "pn": "D48TLPA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0",
    "resolution": "FHD",
    "color": "银色",
    "srp": 9299,
    "real": 5699,
    "cn2": "8174",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook X 360 14 AMD 2026",
    "seriesKey": "starbook",
    "model": "HP OmniBook X 14-kc0002AU",
    "pn": "D48TMPA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "1TB SSD",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 10899,
    "real": 6999,
    "cn2": "9657",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook X 360 14 AMD 2026",
    "seriesKey": "starbook",
    "model": "HP OmniBook X 14-kc0015AU",
    "pn": "D48TQPA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "1TB SSD",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 13999,
    "real": 7499,
    "cn2": "12502",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook X 360 14 AMD 2026",
    "seriesKey": "starbook",
    "model": "HP OmniBook X 14-kc0003AU",
    "pn": "D48TNPA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "1TB SSD",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 14899,
    "real": 8299,
    "cn2": "13313",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook X 360 14 AMD 2026",
    "seriesKey": "starbook",
    "model": "HP OmniBook X 14-kc0004AU",
    "pn": "D48TPPA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "1TB SSD",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 15499,
    "real": 9299,
    "cn2": "13884",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏂 spectre x360 2024",
    "seriesKey": "spectre",
    "model": "Spectre x360 14-eu0777TU",
    "pn": "9H994PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16 OLED",
    "resolution": "FHD",
    "color": "黑色",
    "srp": 9999,
    "real": 9999,
    "cn2": "9216.05",
    "segment": "premium",
    "highlight": true
  },
  {
    "series": "鏂 spectre x360 2024",
    "seriesKey": "spectre",
    "model": "Spectre x360 14-eu0888TU",
    "pn": "9H995PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16 OLED",
    "resolution": "FHD",
    "color": "蓝色",
    "srp": 13999,
    "real": 13999,
    "cn2": "12020.94",
    "segment": "premium",
    "highlight": true
  },
  {
    "series": "鏂 spectre x360 2024",
    "seriesKey": "spectre",
    "model": "Spectre x360 14-eu0999TU",
    "pn": "9H996PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16 OLED",
    "resolution": "FHD",
    "color": "黑色",
    "srp": 13999,
    "real": 13999,
    "cn2": "12020.94",
    "segment": "premium",
    "highlight": true
  },
  {
    "series": "鏂 spectre x360 2024",
    "seriesKey": "spectre",
    "model": "Spectre x360 16-aa0666TU",
    "pn": "9H997PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16 OLED",
    "resolution": "FHD",
    "color": "黑色",
    "srp": 13999,
    "real": 13999,
    "cn2": "12121.11",
    "segment": "premium",
    "highlight": true
  },
  {
    "series": "鏂 spectre x360 2024",
    "seriesKey": "spectre",
    "model": "Spectre x360 16-aa0888TU",
    "pn": "9H998PA",
    "cpu": "14999",
    "cpuBrand": "Intel",
    "ram": "—",
    "storage": "32G",
    "gpu": "UMA",
    "screen": "UMA",
    "resolution": "FHD",
    "color": "银色",
    "srp": 922,
    "real": 14999,
    "cn2": "聽12",
    "segment": "premium",
    "highlight": true
  },
  {
    "series": "鏂 spectre x360 2024",
    "seriesKey": "spectre",
    "model": "Spectre x360 16-aa0999TX",
    "pn": "9H999PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16 OLED",
    "resolution": "FHD",
    "color": "蓝色",
    "srp": 16999,
    "real": 16999,
    "cn2": "14926",
    "segment": "premium",
    "highlight": true
  },
  {
    "series": "鏄烞ook Ultra 14 2024",
    "seriesKey": "starbook",
    "model": "HP OmniBook Ultra Flip 14-fh0998TU",
    "pn": "B2CT4PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 14999,
    "real": 13999,
    "cn2": "13524",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook Ultra 14 2024",
    "seriesKey": "starbook",
    "model": "HP OmniBook Ultra Flip 14-fh0999TU",
    "pn": "B2CT5PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 14999,
    "real": 13999,
    "cn2": "13524",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook Ultra 14 2024",
    "seriesKey": "starbook",
    "model": "HP OmniBook Ultra Flip 14-fh0111TU",
    "pn": "AU3G3PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 9999,
    "real": 9999,
    "cn2": "9216",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook Ultra 14 2024",
    "seriesKey": "starbook",
    "model": "HP OmniBook Ultra Flip 14-fh0222TU",
    "pn": "AU3G4PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 9999,
    "real": 9999,
    "cn2": "9216",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook Ultra 14 2024",
    "seriesKey": "starbook",
    "model": "HP OmniBook Ultra Flip 14-fh0333TU",
    "pn": "AU3G5PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 12999,
    "real": 11999,
    "cn2": "11520",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook Ultra 14 2024",
    "seriesKey": "starbook",
    "model": "HP OmniBook Ultra Flip 14-fh0555TU",
    "pn": "AU3G8PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 13999,
    "real": 12999,
    "cn2": "12522",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook Ultra 14 2024",
    "seriesKey": "starbook",
    "model": "HP OmniBook Ultra Flip 14-fh0037TU",
    "pn": "B17XRPA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 11999,
    "real": 10999,
    "cn2": "10718.672",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook Ultra 14 2024",
    "seriesKey": "starbook",
    "model": "HP OmniBook Ultra Flip 14-fh0255TU",
    "pn": "B2CT0PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 12999,
    "real": 11999,
    "cn2": "11870.678",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook Ultra 14 2024",
    "seriesKey": "starbook",
    "model": "HP OmniBook Ultra Flip 14-fh0245TU",
    "pn": "B2CS8PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 13999,
    "real": 12999,
    "cn2": "12787.758",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook Ultra 14 2026",
    "seriesKey": "starbook",
    "model": "HP OmniBook Ultra 14-kd0226TU",
    "pn": "D5EJ5PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 12699,
    "real": 9499,
    "cn2": "11149",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook Ultra 14 2026",
    "seriesKey": "starbook",
    "model": "HP OmniBook Ultra 14-kd0225TU",
    "pn": "D5EG5PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 15699,
    "real": 10299,
    "cn2": "13804",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook Ultra 14 2026",
    "seriesKey": "starbook",
    "model": "HP OmniBook Ultra 14-kd0266TU",
    "pn": "D5EK1PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 15699,
    "real": 10299,
    "cn2": "13814",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook Ultra 14 2026",
    "seriesKey": "starbook",
    "model": "HP OmniBook Ultra 14-kd0665TU",
    "pn": "D5EG6PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 16699,
    "real": 11499,
    "cn2": "14485",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook Ultra 14 2026",
    "seriesKey": "starbook",
    "model": "HP OmniBook Ultra 14-kd0666TU",
    "pn": "D5EG7PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 17299,
    "real": 12499,
    "cn2": "15076",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook Ultra 14 2026",
    "seriesKey": "starbook",
    "model": "HP OmniBook Ultra 14-kd0888TU",
    "pn": "D5EG8PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "—",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 23899,
    "real": 13499,
    "cn2": "20816",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook Ultra 14 2026",
    "seriesKey": "starbook",
    "model": "HP OmniBook Ultra 14-kd0889TU",
    "pn": "D5EJ8PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "—",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 23899,
    "real": 13499,
    "cn2": "20836",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook Ultra 14 2026",
    "seriesKey": "starbook",
    "model": "HP OmniBook Ultra 14-kd0998TU",
    "pn": "D5EG9PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "—",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 25999,
    "real": 14499,
    "cn2": "22820",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "鏄烞ook Ultra 14 2026",
    "seriesKey": "starbook",
    "model": "HP OmniBook Ultra 14-kd0999TU",
    "pn": "D5EF3PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "—",
    "storage": "—",
    "gpu": "UMA",
    "screen": "14.0 OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 26999,
    "real": 15499,
    "cn2": "23391",
    "segment": "slim",
    "highlight": false
  },
  {
    "series": "Victus 15 2025",
    "seriesKey": "victus",
    "model": "Victus 15-fa2739TX",
    "pn": "B82KVPA",
    "cpu": "i5-13420H",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 5299,
    "real": 4599,
    "cn2": "4981",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "Victus 15 2025",
    "seriesKey": "victus",
    "model": "Victus 15-fa2705TX",
    "pn": "B82KTPA",
    "cpu": "i5-13420H",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 6299,
    "real": 5199,
    "cn2": "5822",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "Victus 15 2025",
    "seriesKey": "victus",
    "model": "Victus 15-fa2407TX",
    "pn": "B5PW5PA",
    "cpu": "i7-13620H",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 5699,
    "real": 5299,
    "cn2": "5357",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "Victus 15 2025",
    "seriesKey": "victus",
    "model": "Victus 15-fa2015TX",
    "pn": "B5PW3PA",
    "cpu": "Core5210H",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 6999,
    "real": 5799,
    "cn2": "6579",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "Victus 15 2025",
    "seriesKey": "victus",
    "model": "Victus 15-fa2016TX",
    "pn": "B5PW4PA",
    "cpu": "Core5210H",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 6999,
    "real": 5799,
    "cn2": "6579",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "Victus 15 2025",
    "seriesKey": "victus",
    "model": "Victus 15-fa2328TX",
    "pn": "BN5H7PA",
    "cpu": "i7-13620H",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 7299,
    "real": 6499,
    "cn2": "6861",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "Victus 15 2025",
    "seriesKey": "victus",
    "model": "Victus 15-fa2346TX",
    "pn": "BN5J0PA",
    "cpu": "i7-13620H",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 7699,
    "real": 7299,
    "cn2": "7237",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "Victus 15 2025 AMD",
    "seriesKey": "victus",
    "model": "Victus15-fb3246AX",
    "pn": "D2TR4PA",
    "cpu": "—",
    "cpuBrand": "AMD",
    "ram": "—",
    "storage": "—",
    "gpu": "UMA",
    "screen": "",
    "resolution": "FHD",
    "color": "银色",
    "srp": 7799,
    "real": 7299,
    "cn2": "7456",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "Victus 15 2025 AMD",
    "seriesKey": "victus",
    "model": "Victus15-fb3248AX",
    "pn": "D2TR7PA",
    "cpu": "—",
    "cpuBrand": "AMD",
    "ram": "—",
    "storage": "—",
    "gpu": "UMA",
    "screen": "",
    "resolution": "FHD",
    "color": "银色",
    "srp": 7199,
    "real": 6799,
    "cn2": "6882",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "OMEN SILM 2024",
    "seriesKey": "omenslim",
    "model": "OMEN SLIM 14-fb0051TX",
    "pn": "9S4L4PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 10999,
    "real": 10999,
    "cn2": "10683",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "OMEN SILM 2024",
    "seriesKey": "omenslim",
    "model": "OMEN SLIM 14-fb0055TX",
    "pn": "9T8Z4PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "",
    "resolution": "FHD",
    "color": "银色",
    "srp": 11999,
    "real": 11999,
    "cn2": "11654",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "OMEN SILM 2024",
    "seriesKey": "omenslim",
    "model": "OMEN SLIM 14-fb0064TX",
    "pn": "9T0M0PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "",
    "resolution": "FHD",
    "color": "银色",
    "srp": 13999,
    "real": 13999,
    "cn2": "13596",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "OMEN SILM 2024",
    "seriesKey": "omenslim",
    "model": "OMEN SLIM 14-fb0061TX",
    "pn": "9T0L9PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 10999,
    "real": 10999,
    "cn2": "10683",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "OMEN SILM 2024",
    "seriesKey": "omenslim",
    "model": "OMEN SLIM 14-fb0062TX",
    "pn": "9T8Z0PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "",
    "resolution": "FHD",
    "color": "银色",
    "srp": 11999,
    "real": 11999,
    "cn2": "11654",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "OMEN SILM 2024",
    "seriesKey": "omenslim",
    "model": "OMEN SLIM 14-fb0065TX",
    "pn": "9T0M1PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "",
    "resolution": "FHD",
    "color": "银色",
    "srp": 13999,
    "real": 13999,
    "cn2": "13596",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "OMEN SILM 2024",
    "seriesKey": "omenslim",
    "model": "OMEN SLIM 16-u1024TX",
    "pn": "9T906PA",
    "cpu": "i9-14900HX",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "",
    "resolution": "FHD",
    "color": "银色",
    "srp": 11499,
    "real": 10999,
    "cn2": "11168",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "OMEN SILM 2024",
    "seriesKey": "omenslim",
    "model": "OMEN SLIM 16-u1025TX",
    "pn": "9T3L1PA",
    "cpu": "i9-14900HX",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "",
    "resolution": "FHD",
    "color": "银色",
    "srp": 13999,
    "real": 13999,
    "cn2": "13596",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "OMENSILM2025",
    "seriesKey": "omen",
    "model": "OMEN SILM 14-fb1085TX",
    "pn": "C28KNPA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 12499,
    "real": 11999,
    "cn2": "11949",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "OMENSILM2025",
    "seriesKey": "omen",
    "model": "OMEN SILM 14-fb1086TX",
    "pn": "C28KPPA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 12699,
    "real": 12199,
    "cn2": "12140",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "OMENSILM2025",
    "seriesKey": "omen",
    "model": "OMEN SILM 14-fb1087TX",
    "pn": "C28KQPA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 13999,
    "real": 13499,
    "cn2": "13383",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "OMENSILM2025",
    "seriesKey": "omen",
    "model": "OMEN SILM 14-fb1088TX",
    "pn": "C28KRPA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 14199,
    "real": 13699,
    "cn2": "13574",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "OMENSILM2025",
    "seriesKey": "omen",
    "model": "OMEN SILM 14-fb1098TX",
    "pn": "C28KSPA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "—",
    "storage": "—",
    "gpu": "UMA",
    "screen": "OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 16499,
    "real": 15499,
    "cn2": "15773",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "OMENSILM2025",
    "seriesKey": "omen",
    "model": "OMEN SILM 14-fb1099TX",
    "pn": "C28KTPA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "—",
    "storage": "—",
    "gpu": "UMA",
    "screen": "OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 16699,
    "real": 15699,
    "cn2": "15964",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "OMEN MAX 2025",
    "seriesKey": "omenmax",
    "model": "OMEN MAX 16-ah0239TX",
    "pn": "CK0Z1PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 9499,
    "real": 8999,
    "cn2": "9081",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "OMEN MAX 2025",
    "seriesKey": "omenmax",
    "model": "OMEN MAX 16-ah0240TX",
    "pn": "CK1F8PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "",
    "resolution": "FHD",
    "color": "银色",
    "srp": 9999,
    "real": 9499,
    "cn2": "9559",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "OMEN MAX 2025",
    "seriesKey": "omenmax",
    "model": "OMEN MAX 16-ah0002TX",
    "pn": "B90CPPA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "",
    "resolution": "FHD",
    "color": "银色",
    "srp": 15999,
    "real": 14499,
    "cn2": "14339",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "OMEN MAX 2025",
    "seriesKey": "omenmax",
    "model": "OMEN MAX 16-ah0088TX",
    "pn": "B94PMPA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "",
    "resolution": "FHD",
    "color": "银色",
    "srp": 17999,
    "real": 16999,
    "cn2": "15773",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "OMEN MAX 2025",
    "seriesKey": "omenmax",
    "model": "OMEN MAX 16-ah0003TX",
    "pn": "B8BG0PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "",
    "resolution": "FHD",
    "color": "银色",
    "srp": 18999,
    "real": 18499,
    "cn2": "17207",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "OMEN MAX 2025",
    "seriesKey": "omenmax",
    "model": "OMEN MAX 16-ah0089TX",
    "pn": "B9FJ6PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "",
    "resolution": "FHD",
    "color": "银色",
    "srp": 19199,
    "real": 18499,
    "cn2": "17398",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "OMEN MAX 2025",
    "seriesKey": "omenmax",
    "model": "OMEN MAX 16-ah0004TX",
    "pn": "B8BG1PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "",
    "resolution": "FHD",
    "color": "银色",
    "srp": 22999,
    "real": 22999,
    "cn2": "21031",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "OMEN MAX 2025",
    "seriesKey": "omenmax",
    "model": "OMEN MAX 16-ah0005TX",
    "pn": "B9FH8PA",
    "cpu": "—",
    "cpuBrand": "Intel",
    "ram": "—",
    "storage": "—",
    "gpu": "UMA",
    "screen": "OLED",
    "resolution": "FHD",
    "color": "银色",
    "srp": 24999,
    "real": 24999,
    "cn2": "22943",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "鏆楀奖绮剧伒11",
    "seriesKey": "omen",
    "model": "OMEN16-am0024TX",
    "pn": "BP3X0PA",
    "cpu": "i7-14650HX",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 7999,
    "real": 7999,
    "cn2": "7647",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "鏆楀奖绮剧伒11",
    "seriesKey": "omen",
    "model": "OMEN16-am0000TX",
    "pn": "BM7T0PA",
    "cpu": "i7-14650HX",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 8499,
    "real": 8499,
    "cn2": "8125",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "鏆楀奖绮剧伒11",
    "seriesKey": "omen",
    "model": "OMEN 16-am0253TX",
    "pn": "C2JR7PA",
    "cpu": "i7-14650HX",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 8999,
    "real": 8699,
    "cn2": "8603",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "鏆楀奖绮剧伒11",
    "seriesKey": "omen",
    "model": "OMEN 16-am0254TX",
    "pn": "C2JR8PA",
    "cpu": "i7-14650HX",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "",
    "resolution": "FHD",
    "color": "银色",
    "srp": 9499,
    "real": 9699,
    "cn2": "9081",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "鏆楀奖绮剧伒11",
    "seriesKey": "omen",
    "model": "OMEN 16-am0221TX",
    "pn": "C0XU5PA",
    "cpu": "i7-14650HX",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "",
    "resolution": "FHD",
    "color": "银色",
    "srp": 8999,
    "real": 9499,
    "cn2": "8603",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "鏆楀奖绮剧伒11",
    "seriesKey": "omen",
    "model": "OMEN 16-am0411TX",
    "pn": "D2XJ0PA",
    "cpu": "i7-14650HX",
    "cpuBrand": "Intel",
    "ram": "—",
    "storage": "—",
    "gpu": "UMA",
    "screen": "",
    "resolution": "FHD",
    "color": "银色",
    "srp": 8799,
    "real": 9099,
    "cn2": "8412",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "鏆楀奖绮剧伒11",
    "seriesKey": "omen",
    "model": "OMEN16-am0001TX",
    "pn": "BM7T1PA",
    "cpu": "i7-14650HX",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 9499,
    "real": 9299,
    "cn2": "9081",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "鏆楀奖绮剧伒11",
    "seriesKey": "omen",
    "model": "OMEN16-am0002TX",
    "pn": "BM7T2PA",
    "cpu": "i7-14650HX",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "",
    "resolution": "FHD",
    "color": "银色",
    "srp": 9999,
    "real": 10299,
    "cn2": "9559",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "鏆楀奖绮剧伒11",
    "seriesKey": "omen",
    "model": "OMEN16-am0026TX",
    "pn": "BM9A0PA",
    "cpu": "i9-14900HX",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 8999,
    "real": 8999,
    "cn2": "8603",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "鏆楀奖绮剧伒11",
    "seriesKey": "omen",
    "model": "OMEN16-am0003TX",
    "pn": "BM8Z7PA",
    "cpu": "i9-14900HX",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "",
    "resolution": "FHD",
    "color": "银色",
    "srp": 9499,
    "real": 9999,
    "cn2": "9081",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "鏆楀奖绮剧伒11",
    "seriesKey": "omen",
    "model": "OMEN16-am0025TX",
    "pn": "BM8Z9PA",
    "cpu": "i9-14900HX",
    "cpuBrand": "Intel",
    "ram": "16G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "16",
    "resolution": "FHD",
    "color": "银色",
    "srp": 9999,
    "real": 9799,
    "cn2": "9559",
    "segment": "gaming",
    "highlight": false
  },
  {
    "series": "鏆楀奖绮剧伒11",
    "seriesKey": "omen",
    "model": "OMEN16-am0004TX",
    "pn": "BM8Z8PA",
    "cpu": "i9-14900HX",
    "cpuBrand": "Intel",
    "ram": "32G",
    "storage": "—",
    "gpu": "UMA",
    "screen": "",
    "resolution": "FHD",
    "color": "银色",
    "srp": 10499,
    "real": 10799,
    "cn2": "10037",
    "segment": "gaming",
    "highlight": false
  }
];
